services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=code-base-2'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'

  python-filter-service:
    build: ./python-filterer
    container_name: python-filter-service
    ports:
      - '8000:8000'
    labels:
      - "org.springframework.boot.service-connection=python"